content:
  - name: home
    label: Homepage
    type: file
    path: src/content/home.json
    format: json

    fields:
      - name: title
        type: string

      - name: sections
        type: block
        list: true
        blockKey: type

        blocks:
          - name: hero
            label: Hero
            fields:
              - name: id
                type: string
              - name: label
                type: string
              - name: title
                type: string
              - name: subTitle
                type: string
              - name: buttonText
                type: string
              - name: secondaryButtonText
                type: image

          - name: about
            label: About
            fields:
              - name: id
                type: string
              - name: label
                label: Navigation Label
                type: string
              - name: heading
                label: Header
                type: string
              - name: description
                type: text
              - name: image
                type: image

          - name: services
            label: Services

            fields:
              - { name: id, type: text }
              - { name: label, label: Navigation Label, type: text }
              - { name: heading, type: text }

              - name: items
                label: Services
                type: object
                list: true

                fields:
                  - { name: title, type: text }
                  - { name: description, type: text }

          - name: gallery
            label: Gallery

            fields:
              - { name: id, type: text }
              - { name: label, label: Navigation Label, type: text }

              - name: images
                type: image
                list: true

          - name: contact
            label: Contact

            fields:
              - { name: id, type: text }
              - { name: label, label: Navigation Label, type: text }
              - { name: heading, type: text }
              - { name: description, type: text }
              - { name: email, type: text }
              - { name: phone, type: text }
              - { name: address, type: text }
              - { name: buttonText, type: text }